spring:
  config.activate.on-profile: default
  threads.virtual.enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/orders_service
    username: root
    password: "}s9kKa@c3R6/"
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    database: MYSQL
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  error:
    include-message: always
catalog:
  base-url: http://localhost:8081/api
